os:
  - linux
dist: bionic
language: python

# build for all pushes, as well as PRs coming from forks
# this ensures that the pipeline is triggered for internal pushes,
# PRs from forks and pushes to existing PRs from forks
if: (type == push) OR (type == pull_request AND fork == true)


stages:
- name: test
- name: publish
  # for security reasons, builds from forks won't be published until merged;
  # also, environment variables defined in repository settings are not
  # available to builds from PRs coming from external repos
  if: fork == false

jobs:
  include:
    - stage: test
      name: Run linting and unit tests on Python 3.6
      python: 3.6
      script:
        - flake8
        - coverage run --source trs_filer -m pytest
        - coveralls
    - stage: test
      name: Run linting and unit tests on Python 3.7
      python: 3.7
      script:
        - flake8
        - coverage run --source trs_filer -m pytest
        - coveralls
    - stage: test
      name: Run linting and unit tests on Python 3.8
      python: 3.8
      script:
        - flake8
        - coverage run --source trs_filer -m pytest
        - coveralls
    - stage: publish
      name: Build and publish
      python: 3.8
      services:
        - docker
      before_script:
        - |
          export
          if [ "$TRAVIS_BRANCH" = "dev" ]; then
              export DOCKER_TAG="$(date '+%Y%m%d')"
          else
              export DOCKER_TAG=${TRAVIS_BRANCH//_/-}
              export DOCKER_TAG=${DOCKER_TAG//\//-}
          fi
      script:
        - |
          docker build . \
            -t "${DOCKER_REPO_NAME}:latest" \
            -t "${DOCKER_REPO_NAME}:${DOCKER_TAG}"
        - |
          echo "${DOCKER_TOKEN}" | \
            docker login -u "${DOCKER_USER}" --password-stdin
        - docker push "${DOCKER_REPO_NAME}:${DOCKER_TAG}"
        - |
          if [ "$TRAVIS_BRANCH" = "dev" ]; then
            docker push "${DOCKER_REPO_NAME}:latest"
          fi
        - rm ${HOME}/.docker/config.json  # delete token
