version: '3.6'
services:

    trs:
        image: elixircloud/trs-filer:latest
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        links:
            - mongodb
        command: bash -c "cd /app/trs_filer; gunicorn -c gunicorn.py wsgi:app"
        ports:
            - "8080:8080"

    mongodb:
        image: mongo:3.6
        restart: unless-stopped
        volumes:
            - ../data/trs/db:/data/db
        ports:
            - "27017:27017"
