version: '3.6'
services:

    trs:
        image: elixircloud/trs-filer:0.1.0
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        links: 
            - mongodb
        command: bash -c "cd /app/trs_filer; python app.py"
        ports:
            - "3888:8080"

    mongodb: 
        image: mongo:3.6
        restart: unless-stopped
        ports:
            - "24017:27017"
