apiVersion: v1
kind: Service
metadata:
  name: trs-filer
spec:
  ports:
  - name: trs-filer
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: trs-filer
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
