apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.trs_filer.appName }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.trs_filer.appName }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.trs_filer.appName }}
    spec:
      containers:
      - image: {{ .Values.trs_filer.image }}
        imagePullPolicy: Always
        name: {{ .Values.trs_filer.appName }}
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/trs_filer/config.yaml
          name: config-yaml
          subPath: config.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
            - key: config.yaml
              path: config.yaml
          name: app-config
        name: config-yaml
status:
