{{ if eq .Values.clusterType "openshift" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.trs_filer.appName }}
spec:
  host: {{ .Values.host_name }}
  port:
    targetPort: {{ .Values.trs_filer.appName }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Values.trs_filer.appName }}
    weight: 100
  wildcardPolicy: None
status:
  ingress: []
{{ end }}
