server:
    host: '0.0.0.0'
    port: 8080
    debug: True
    environment: development
    testing: False
    use_reloader: False

db:
    host: mongodb
    port: 27017
    dbs:
        trsStore:
            collections:
                objects:
                    indexes:
                        - keys:
                              id: 1
                          options:
                            'unique': True

api:
    specs:
        - path:
            - api/20200728.1059c7c.openapi.yaml
            - api/20200131.11d2c12.service-info.yaml
            - api/additions.openapi.yaml
          append: null
          add_operation_fields:
              x-openapi-router-controller: ga4gh.trs.server
          connexion:
              strict_validation: True
              validate_responses: True
              options:
                  swagger_ui: True
                  serve_spec: True

log:
    version: 1
    disable_existing_loggers: False
    formatters:
        standard:
            class: logging.Formatter
            style: "{"
            format: "[{asctime}: {levelname:<8}] {message} [{name}]"
    handlers:
        console:
            class: logging.StreamHandler
            level: 20
            formatter: standard
            stream: ext://sys.stderr
    root:
        level: 10
        handlers: [console]

exceptions:
    required_members: [['message'], ['code']]
    status_member: ['code']
    exceptions: trs_filer.errors.exceptions.exceptions

endpoints:
    tool:
        id:
            charset: string.ascii_uppercase + string.digits
            length: 6
        meta_version:
            init: 1
            increment: 1
    tool_version:
        id:
            charset: string.ascii_lowercase + string.digits
            length: 6
        meta_version:
            init: 1
            increment: 1
    url_prefix: http
    external_host: 1.2.3.4
    external_port: 3888
    api_path: ga4gh/trs/v2
