# Default values for trs-filer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

host_name: trs-filer-test.2.rahtiapp.fi

trs_filer:
  image: elixircloud/trs-filer:latest
  appName: trs-filer

apiServer: kubernetes.default.svc:443 # address of k8s API server

# If you are running kubernetes select whether you would like
# to access the service via Ingress. Also, if you have the cert manager
# installed, you can provision a certificate for https
kubernetes:
  ingress:
    enabled: true
  https:
    enabled: true
    issuer: letsencrypt-prod

mongodb:
  image: mongo:8.0.9
  volumeSize: 1Gi

minio:
  image: minio/minio:latest
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: trs-files
  volumeSize: 10Gi
  consolePort: 9001
  apiPort: 9000
  endpoint: http://minio-trs-filer:9000
  publicEndpoint: http://localhost:9000

fileStorage:
  strategy: minio

