# Default values for trs-filer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

clusterType: openshift

host_name: trs-filer-test.c03.k8s-popup.csc.fi

trs_filer:
  image: lvarin/trs-filer:0.1.0

mongodb:
  image: mongo:3.6
  volumeSize: 1Gi
