paths:
  "/tools/":
    post:
      description: Create a tool object.
      operationId: addTool
      requestBody:
        description: Tool to add to the TRS store
        required: true
        content:
          application/json:
            schema:
              x-body-name: tool
              $ref: '#/components/schemas/Tool'
      responses:
        '200':
          description: tool response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tool'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  "/tools/{id}/versions/{version_id}/{type}/descriptor":
    post:
      description: Create the tool descriptor for the specified tool
      operationId: addFileWrapper
      parameters:
        - name: type
          required: true
          in: path
          description: The output type of the descriptor. Plain types return the bare
            descriptor while the "non-plain" types return a descriptor wrapped
            with metadata. Allowable values include "CWL", "WDL", "NFL",
            "GALAXY", "PLAIN_CWL", "PLAIN_WDL", "PLAIN_NFL", "PLAIN_GALAXY".
          schema:
            type: string
        - name: id
          in: path
          description: A unique identifier of the tool, scoped to this registry, for
            example `123456`.
          required: true
          schema:
            type: string
        - name: version_id
          in: path
          required: true
          description: An identifier of the tool version, scoped to this registry, for
            example `v1`.
          schema:
            type: string
      requestBody:
        description: Tool descriptor for a particular tool in the TRS store
        required: true
        content:
          application/json:
            schema:
              x-body-name: filewrapper
              $ref: '#/components/schemas/FileWrapper'
      responses:
        '200':
          description: filewrapper response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileWrapper'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  "/tools/{id}/versions/{version_id}/{type}/files":
    post:
      description: Create files of specific type for a particular version of a tool.
      operationId: addToolFiles
      parameters:
        - name: type
          required: true
          in: path
          description: The output type of the descriptor. Examples of allowable values are
            "CWL", "WDL", "NFL", "GALAXY".
          schema:
            type: string
        - name: id
          in: path
          description: A unique identifier of the tool, scoped to this registry, for
            example `123456`.
          required: true
          schema:
            type: string
        - name: version_id
          in: path
          required: true
          description: An identifier of the tool version for this particular tool
            registry, for example `v1`.
          schema:
            type: string
      requestBody:
        description: All tool files to the tool in TRS store
        required: true
        content:
          application/json:
            schema:
              x-body-name: toolfile
              $ref: '#/components/schemas/ToolFile'
      responses:
        '200':
          description: toolfile response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToolFile'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /toolClasses:
    post:
      description: Create tool types
      operationId: addToolClasses
      requestBody:
        description: Add tool classes
        required: true
        content:
          application/json:
            schema:
              x-body-name: toolclass
              $ref: '#/components/schemas/ToolClass'
      responses:
        '200':
          description: toolclass response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToolClass'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  "/tools/{id}/versions":
    post:
      description: Create tool version of a particular tool.
      operationId: addToolVersion
      parameters:
        - name: id
          in: path
          required: true
          description: A unique identifier of the tool, scoped to this registry, for
            example `123456`.
          schema:
            type: string
      requestBody:
        description: Add tool version
        required: true
        content:
          application/json:
            schema:
              x-body-name: toolversion
              $ref: '#/components/schemas/ToolVersion'
      responses:
        '200':
          description: toolversion response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToolVersion'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
