paths:
  "/tools/":
    post:
      description: Create a tool object.
      operationId: addTool
      requestBody:
        description: Tool to add to the TRS store
        required: true
        content:
          application/json:
            schema:
              x-body-name: tool
              $ref: '#/components/schemas/Tool'
      responses:
        '200':
          description: tool response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tool'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
